// <auto-generated />
using System;
using DistributedExceptionHandling.Worker.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DistributedExceptionHandling.Worker.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DistributedExceptionHandling.Worker.Model.ExceptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<DateTime>("OcurredExceptionDate");

                    b.Property<string>("Origin")
                        .IsRequired();

                    b.Property<DateTime>("QueuePulledExceptionDate");

                    b.Property<string>("RequestedUri")
                        .IsRequired();

                    b.Property<string>("StatusCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DistributedException");
                });
#pragma warning restore 612, 618
        }
    }
}
